### ISSUE TITLE
@ Dorian: E-Mail-Anfrage von J. Kemper

### ISSUE THREAD

**Issue by salutHH** [Dumbaz/KarlLutz#1]
Hi Dorian,

J. Kemper haben wir unsere E-Mail-Adressen weitergeleitet. Würdest du ihm deine noch zukommen lassen?

Liebe Grüße aus Hamburg
Samantha

---

Liebe Frau Lutz,

noch eine Frage: der Entwickler am Tisch (mit dem ich über die Frage der Ortsbezeichnungen usw. gesprochen habe) – unter welcher Mailadresse ist er zu erreichen?
Wir haben ja zugesagt, dass wir die nächsten 1-2 Wochen die XML-Daten verbessern; soweit ich sehe, ist er nicht unter den Mailadressen (oder doch?)?
Herzlich 
JK

**Comment by Dumbaz** [comment]
Er hat mich auch noch auf Twitter kontaktiert, ich habe ihm meine Mail jetzt auch gegeben.
