### ISSUE TITLE
Hackdash Eintrag

### ISSUE THREAD

**Issue by Dumbaz** [Dumbaz/KarlLutz#3]
Haben wir noch nicht.

Wenn sich jemand erbarmen würde:
http://hackdash.org/dashboards/cdv15

**Comment by LeGiz** [comment]
haben wir schon...
"wasserspeyer"
es gibt das ganze sogar 2x.
@ samantha vielleicht kannst du eins wieder löschen ;).

lg
sandra

Am 27.04.15 um 22:58 schrieb Dumbaz:

**Comment by Dumbaz** [comment]
Irgendwie hatte ich das nicht gesehen, als ich selbst nachgeschaut hatte. Bleibt nur noch, es zu löschen.

Du kannst übrigens eine Person mit einem @ und dann aus der Liste aussuchen hier verlinken:

@salutHH

**Comment by salutHH** [comment]
seltsam... der 2. Eintrag im Hackdash ist nun gelöscht.
